### ISSUE TITLE
Update legacy componentWillReceiveProps method 

### ISSUE THREAD

**Issue by JuliaSklyar** [drivetribe/react-intersection#3]
Hi @InventingWithMonster !

Could you please update this method https://github.com/drivetribe/react-intersection/blob/master/src/IntersectionRoot.js#L34.

According to React 16.3 version changes https://reactjs.org/blog/2018/03/29/react-v-16-3.html `componentWillReceiveProps` is deprecated now. You can use `shouldComponentUpdate` (which is not ideal) or `componentDidUpdate` instead of `componentWillReceiveProps`.

Thanks!

**Comment by soiluong** [comment]
Done
